### ISSUE TITLE
完成までの ToDo Flow

### ISSUE THREAD

**Issue by Yusuke-Yamasaki-555** [open-rdc/ROS2_Walking_Pattern_Generator#25]
- [ ] WPGの開発
- [ ] ロボットの各種情報をRviz2で可視化
  - [ ] Webots内のロボットの動作周期が時々狂う問題
  - [ ] Webots内のロボットの動作周期を設定
  - [ ] ros2_controlへの対応
- [ ] WSCの開発
- [ ] 動歩行の実装
- [ ] Life Cycleの構成、設定、適用
- [ ] ParameterServerの実装、移行
- [ ] QoSの設定の追加、調整
- [ ] ロボットモデルのURDFへの移行
- [ ] pinocchioへの移行と実装

**Comment by Yusuke-Yamasaki-555** [comment]
動歩行の実装は、ある程度達成した。動歩行動作生成を、WPG nodeへ移行していく。

**Comment by Yusuke-Yamasaki-555** [comment]
WPG化は済んでいるが、pub/subのせいかdata lossがちょいある。service通信を検討するためにissueは閉じない。

**Comment by Yusuke-Yamasaki-555** [comment]
直近やるべきTODO

- [x] URDF to YAML Scriptで、四肢を選択してもらう機能追加
  - [x] 機能のみの追加
  - [x] 四肢それぞれの関節ごとの関節情報をまとめたListのParameterを追加
  - [ ] UIの整形
- [x] URDF to YAML ScriptとRobotisOp2 URDFをRepositoryに適用
- [x] YAMLのParameter化、及び動作確認
- [x] Parameterを用いたコードにリファクタリング、及び動作確認
- [ ] CtJSのリファクタリング（雑多なコードの整理による動作時間の短縮を目的）
- [ ] README.md, Wiki, Blogの整備（ドキュメント整備と充実）
- [ ] 数値的手法のInverseKinematics Pluginを開発、及び動作確認
- [ ] InverseKinematicsを解析的手法から数値的手法へ差し替え、及び動作確認
- [ ] WPGとFSPのバグの有無を確認、及び歩行動作の質の向上
